#!/bin/sh
 # Write a shell script which takes as parameters a short month name followed by a day number (ex: Mar 8). The script will display all user accounts that were connected to the server that day of month.
