#!/bin/sh

# Write a shell script which takes as parameters a lowercase letter followed
# by several file names. The script will replace each digit with the letter
# given as a parameter in all given files.
