#!/bin/sh

# Write a shell script which takes as parameters several file names. The
# script will replace the 3rd word with the 1st word in each line of the given
# files. The words shall contain only letters or numbers and shall be
# separated by ":".
#
if [ $# -lt 1 ]; then
    echo "Usage: $0 <file1> <file2> ..."
    exit 1
fi

# ONE LINER BABY
sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/g' "${@}"
