#!/bin/sh
 # Write a shell script which takes as parameters several file names. The script will replace the 3rd word with the 1st word in each line of the given files. The words shall contain only letters or numbers and shall be separated by ":".
