#!/bin/bash

# Write a shell script which takes as parameters an uppercase letter followed
# by several file names. The script will add the given letter in the front of
# each lowercase on each line in all given files.

if [ $# -lt 2 ]; then
    echo "Usage: $0 <uppercase letter> <file1> <file2> ..."
    exit 1
fi

# i will solely trust the user to provide a valid uppercase letter, thanks
letter=$1

# ensure the letter is uppercase
letter=${letter^}

# ONE LINER BABY
sed -i "s/\<[a-z]/$1&/g" "${@:2}"

