#!/bin/sh
 # Write a Shell program that, starting with the directory given as a first parameter, downwards (recursively), creates a list of all names that appear (files and directory), and for each filename it prints the number of files with the same name.
