#!/bin/sh
 # Write a shell script which takes as parameters several file names. For each line in the given files which contains more than 20 characters, the script will display the number of that line, the first word and the last word.
