#!/bin/sh
 # Write a shell script that takes as parameters several file names. For each line in the given files in which a word appears 2 or more times, the script will display the number of that line, and the word involved.
