#!/bin/sh
# Write a shell script which takes as parameters two integers. The script will
# display the sum, the difference and the product of the two given integers.
#
# Example:
# ./pb1 3 5
# 3 + 5 = 8
# 3 - 5 = -2
# 3 * 5 = 15
#
#
# check for parameters:
if [ $# -ne 2 ]; then
    echo "Incorrect number of parameters"
    echo "Usage: $0 <integer1> <integer2>"
    exit 1
fi

# check if the parameters are integers
if ! [ "$1" -eq "$1" ] 2>/dev/null || ! [ "$2" -eq "$2" ] 2>/dev/null; then
    echo "The parameters must be integers"
    echo "Usage: $0 <integer1> <integer2>"
    exit 1
fi

sum=$(($1 + $2))
diff=$(($1 - $2))
prod=$(($1 * $2))

echo "$1 + $2 = $sum"
echo "$1 - $2 = $diff"
echo "$1 * $2 = $prod"
