#!/bin/sh

# Main script
echo "Listing contents of the current directory:"
echo "-----------------------------------------"

echo "Files sorted by name:"
find . -maxdepth 1 -type f -exec basename {} \; | sort
echo

echo "Files sorted by last modified date:"
find . -maxdepth 1 -type f -exec stat -c '%Y %n' {} \; | sort -n | awk '{print $2}' | xargs -I{} basename {}
echo

echo "Files sorted by file size:"
find . -maxdepth 1 -type f -exec stat -c '%s %n' {} \; | sort -n | awk '{print $2}' | xargs -I{} basename {}
