#!/bin/sh
 # Write a Shell program that supervises the system, such that: each time certain users (given as parameters) connect to or disconnect from the system, it will save in a file the username, time, if it’s new connection or disconnection, and the server on which the action was made.
